In [1]:
import os
import pandas as pd

path = r"C:\Users\Administrator\Documents\IPL Data"

os.chdir(path)

os.listdir(path)

ball = pd.read_excel("Ball_by_Ball.xlsx")

match = pd.read_excel("Match.xlsx")

player = pd.read_excel("Player.xlsx")

player_match = pd.read_excel('Player_Match.xlsx')

season = pd.read_excel('Season.xlsx')

team = pd.read_excel('Team.xlsx')

In [3]:
match1 = match[['Team_Name_Id', 'Toss_Winner_Id', 'Toss_Decision', 'Opponent_Team_Id']]
match1.head(1)

   Team_Name_Id  Toss_Winner_Id Toss_Decision  Opponent_Team_Id
0             2               2         field                 1

In [4]:
ball1=ball[['Innings_Id','Team_Batting_Id','Striker_Id','Team_Bowling_Id']]
ball1.head(1)

   Innings_Id  Team_Batting_Id  Striker_Id  Team_Bowling_Id
0           1                1           1                2

In [5]:
mrg=pd.merge(match1,ball1,left_on="Team_Name_Id",right_on="Team_Batting_Id")

In [8]:
filter1 = mrg[(mrg['Team_Name_Id']==3)&
                 (mrg['Toss_Winner_Id']==3)&
                 (mrg['Toss_Decision']=='bat')&
                 (mrg['Toss_Decision']=='bat')&
                 (mrg['Opponent_Team_Id']==7)]

In [9]:
filter1.head()

,Team_Name_Id,Toss_Winner_Id,Toss_Decision,Opponent_Team_Id,Innings_Id,Team_Batting_Id,Striker_Id,Team_Bowling_Id
6825704,3,3,bat,7,1,3,17,4
6825705,3,3,bat,7,1,3,17,4
6825706,3,3,bat,7,1,3,17,4
6825707,3,3,bat,7,1,3,18,4
6825708,3,3,bat,7,1,3,18,4

In [11]:
filter2=filter1[filter1['Striker_Id']==21]
filter2.head()

,Team_Name_Id,Toss_Winner_Id,Toss_Decision,Opponent_Team_Id,Innings_Id,Team_Batting_Id,Striker_Id,Team_Bowling_Id
6825749,3,3,bat,7,1,3,21,4
6825752,3,3,bat,7,1,3,21,4
6825753,3,3,bat,7,1,3,21,4
6825755,3,3,bat,7,1,3,21,4
6825756,3,3,bat,7,1,3,21,4

In [13]:
filter3=filter2[filter2['Match_Id']]
filter3

KeyError: 'Match_Id'